name: Docker

on:
  workflow_run:
    workflows:
      - "test"
    branches: [ main ]
    types:
      - completed

      
permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: write
    
jobs:
  Docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      
    defaults:
      run:
        working-directory: ./
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get the version to publish
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build to DockerHub
        working-directory: ./flask-pastebin
        run: docker build -t $DOCKERHUB_USERNAME/deadbycloud:latest .

      - name: Push to DockerHub
        working-directory: ./flask-pastebin
        run: docker push $DOCKERHUB_USERNAME/deadbycloud:latest
